name: Python application

on:
  schedule:
    - cron: '*/5 * * * *'  # Hər 5 dəqiqədən bir işləyəcək
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Yeni versiya

    - name: Set up Python
      uses: actions/setup-python@v4  # Yeni versiya
      with:
        python-version: '3.x'
    - name : telethon yukle
      run : |
        pip install telethon
    - name: Run script
      run: |
        python main.py
